export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const USER_SIGNUP_REQUEST_SUCCESS = 'USER_SIGNUP_REQUEST_SUCCESS';

export const LOAD_EXTERNAL_LOGINS = 'LOAD_EXTERNAL_LOGINS';

export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';
export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';
export const DISCONNECTED = 'DISCONNECTED';